### ISSUE TITLE
fail to open the localhost, connection error

### ISSUE THREAD

**Issue by gabrielcha2018** [rlaiola/relax-api#1]
after i run the yarn serve, i went to localhost but it disconnect. and then i ran the curl api call, i got this following message: 
![image](https://user-images.githubusercontent.com/86988332/180621309-e71c805c-60ff-442b-b6b2-faf430709f59.png)

**Comment by gabrielcha2018** [comment]
thank you =

**Comment by rlaiola** [comment]
@gabrielcha2018, thanks for reporting the issue. Basically, the changes include:

- Update puppeteer package to fix node-fetch vulnerability (patched version > 2.6.7);
- Update to the latest code changes from the main repo.

I also created a docker image aiming at easying the deployment process. You can find details at https://github.com/rlaiola/relax-docker

Cheers!
